---
development:
  cloud_name: miracle-anyanwu
  api_key: '313628125845229'
  api_secret: 9POxJojp_iKfipr5ksJM9Nlsa7Y
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: miracle-anyanwu
  api_key: '313628125845229'
  api_secret: 9POxJojp_iKfipr5ksJM9Nlsa7Y
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: miracle-anyanwu
  api_key: '313628125845229'
  api_secret: 9POxJojp_iKfipr5ksJM9Nlsa7Y
  enhance_image_tag: true
  static_image_support: false